### PR TITLE
Check for invalid usernames

### PR DESCRIPTION
**Pull request by mrassili**
This is my first PR

### CODE REVIEW

**Comment by zurda** [comment]
LGTM, thanks for contributing @mrassili. 
I'll add info the to the contributors file soon (as part of [this](https://github.com/zurda/Github-Info/issues/22)), but in the meantime I'll add your name to the file

**Comment by zurda** [comment]
Closes https://github.com/zurda/Github-Info/issues/20

**Comment by mrassili** [comment]
Thanks

**Comment by zurda** [comment]
@all-contributors please add @mrassili  for code

**Comment by zurda** [comment]
@all-contributors please add @mrassili for code

**Pull request merged**
