### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by ksenousi**
I initialised eslint and used the airbnb style format. let me know if you prefer another format.
Also formatted the flash message component accordingly.

Let me know what you think.

#66

### CODE REVIEW

**Comment by zurda** [comment]
@ksenousi , I've never used a linter in my projects before. 
Can you add guidance as to how to run the linter so I can add it to the README file? 
Also, from my understanding, we might want to add the script to `package.json` to run the linter, shouldn't we?
Thanks in advance!

**Comment by ksenousi** [comment]
So there are two ways to use the ESLint, either using the command line or using a plugin for the text editor of choice. I am using Visual Studio code with an ESLint plugin.

The ESLint website provides a list of plugins for popular text editors https://eslint.org/docs/user-guide/integrations 

Using the command line is also possible. I could add the eslint command to the package.json.
For example, to run it enter "npm run lint FILE_PATH"
If the code isn't formatted properly the errors will show, otherwise nothing shows up.

Using a plugin is much easier however.

What do you think @zurda ?

**Comment by zurda** [comment]
Awesome! I'll give it a try, and thanks for explaining :) The plugin sounds great!

**Comment by zurda** [comment]
@all-contributors please add @ksenousi  for code

**Pull request merged**
