### PR TITLE
Add and implement flash messages and not found error handling

### PR DESCRIPTION
**Pull request by ksenousi**
I added a flash messages component and implemented it in GetInfo.js. I wasn't sure if tabs or spaces were preferred so I used tabs for the GetInfo.js. Please review and let me know what you think.

### CODE REVIEW

**Comment by zurda** [comment]
LGTM @ksenousi, thanks for contributing! 

There's a flash of what I believe is the loading message when refreshing the page, but we can address it in a new issue if it turns out to be very noticeable. 

Resolves  https://github.com/zurda/Github-Info/issues/31

**Comment by zurda** [comment]
I think it looks great, @ksenousi . I think the first time I looked the loading was really fast (because the data was cached), but tried again now, and I think it looks great actually. Thanks again!

**Comment by ksenousi** [comment]
Awesome! Thanks for the feedback @zurda.

**Comment by zurda** [comment]
Sure thing, @ksenousi ! Feel free to suggest issues. I'm currently adding the repos :) which should add some data to the page and maybe we can add interesting ways to display the data

**Pull request merged**
