### PR TITLE
Removed Loading field

### LINKED ISSUE #12: Handle slow loading
At the moment, there's a `loading` field that appears before the very first api call is made. You can see it flashes just at the bottom of the black header. This is a bug, and should appear elsewhere.  

Edit: perhaps if the div was a little lower it would be better displayed when the loading is taking time

### PR DESCRIPTION
**Pull request by decarbonite**
Fixes #12

### CODE REVIEW

**Comment by zurda** [comment]
Thanks for the contribution, @decarbonite. Do you think instead of removing the field you could just located it lower in the page, so it's not hidden over the header? 

Sorry for not specifying this in the original issue, but I think some indication that the loading is taking longer than expected is great feedback for the user, and we should keep it. Let me know what you think!

**Comment by decarbonite** [comment]
Couldn't agree more. :)
Will change it immediately.

**Comment by zurda** [comment]
Awesome, @decarbonite . Also, feel free to share what you think about the fact we're just randomaly displaying a user on the first load. This was a great test for me to see everything works properly, but I'm now trying to find another elegant idea for a welcome display. LMK what you think!

**Comment by zurda** [comment]
LGTM, thanks!

**Comment by zurda** [comment]
@all-contributors please add @decarbonite  for enhancements

**Comment by zurda** [comment]
@all-contributors please add @decarbonite  for code

**Pull request merged**
